language: java
after_success:
- "./gradlew cobertura coveralls"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
git:
  depth: 3
deploy:
  provider: releases
  api_key:
    secure: gLt5cVu4zuCzBAEcnmJwk/ZhLw50sn8asjd5SA0PDAcwW1BFJSHI4XUMro+UqIalO2YvWTTOMAV/WjHoYjwbAmAoM0IUpjbXtnqfgzD7s9P5Nr771mHjTIcur2mvFKhCMRa9KqFwQkiV6+8OdLbNHh4cdgmVzuyAAwWkc7ZoKCSJk4VPjYaaC3yujk6uri06bi9xfXDgGcVHQRgPT7uYqiwBxGX6BguudFPG39NZaXKR9fc8drPxKDs+SfoPLen1KHy7TrHzy+urDVin3npkYJz61FbyD7nI+giMSare+t+9Ulra+WcpUUTMxQZrvkes8D76tZXhwRF9VShHNDLJ7vjHZP53S3yVfa1uQ41kXGRf79a7tEsVE9P7EGm5z8M1HgKVndo8xUJXHbwQZq0afnmxnk40jJwdrmCMaDEv4C1gNwG+DNCN0bDII0U/FsMwbE6YdTUFmTbM2iALcgwlz4CsG0PxAP+ll+MjuVogLFH/te4jlDv+i8TGpApW/0b53aAVonKEUA3xboQ4YAju6itn8ySEXBy8TA/UhfoSfwqsGhDekUR0Cg/sklPsaJqNAXqyj7HT2StlxjIaIhRs9ZFvpo37ITABN8bgPZHeM7ARHa462jipaS1shWBuNnrIqDjvfGgkY7kndEw2kLXLAvtQn+wKD0Q7HcHnqBsqulE=
  file_glob: true
  file: build/jfx/app/*
  on:
    repo: GoSuji/Suji
    tags: true
